In [1]:
import pandas as pd
import numpy as np
import requests

## Задание 1. Загрузка данных
Изучить представленный набор данных на основе описания его столбцов, загрузить его и оставить 8 столбцов для дальнейшего изучения: surgery?, Age, rectal temperature, pulse, respiratory rate, temperature of extremities, pain, outcome.

In [39]:
data = pd.read_csv('https://raw.githubusercontent.com/obulygin/pyda_homeworks/master/statistics_basics/horse_data.csv', na_values='?')
data

2  1   530101  38.50     66    28    3  3.1    ?  2.1  ...  45.00  \
0    1.0  1   534817   39.2   88.0  20.0  NaN  NaN  4.0  1.0  ...   50.0   
1    2.0  1   530334   38.3   40.0  24.0  1.0  1.0  3.0  1.0  ...   33.0   
2    1.0  9  5290409   39.1  164.0  84.0  4.0  1.0  6.0  2.0  ...   48.0   
3    2.0  1   530255   37.3  104.0  35.0  NaN  NaN  6.0  2.0  ...   74.0   
4    2.0  1   528355    NaN    NaN   NaN  2.0  1.0  3.0  1.0  ...    NaN   
..   ... ..      ...    ...    ...   ...  ...  ...  ...  ...  ...    ...   
294  1.0  1   533886    NaN  120.0  70.0  4.0  NaN  4.0  2.0  ...   55.0   
295  2.0  1   527702   37.2   72.0  24.0  3.0  2.0  4.0  2.0  ...   44.0   
296  1.0  1   529386   37.5   72.0  30.0  4.0  3.0  4.0  1.0  ...   60.0   
297  1.0  1   530612   36.5  100.0  24.0  3.0  3.0  3.0  1.0  ...   50.0   
298  1.0  1   534618   37.2   40.0  20.0  NaN  NaN  NaN  NaN  ...   36.0   

     8.40  ?.4  ?.5  2.2  2.3  11300  00000  00000.1  2.4  
0    85.0  2.0  2.0  3.0    2   2208      0        0    2  
1     6.7  NaN  NaN  1.0    2      0      0        0    1  
2     7.2  3.0  5.3  2.0    1   2208      0        0    1  
3     7.4  NaN  NaN  2.0    2   4300      0        0    2  
4     NaN  NaN  NaN  1.0    2      0      0        0    2  
..    ...  ...  ...  ...  ...    ...    ...      ...  ...  
294  65.0  NaN  NaN  3.0    2   3205      0        0    2  
295   NaN  3.0  3.3  3.0    1   2208      0        0    1  
296   6.8  NaN  NaN  2.0    1   3205      0        0    2  
297   6.0  3.0  3.4  1.0    1   2208      0        0    1  
298  62.0  1.0  1.0  3.0    2   6112      0        0    2  

[299 rows x 28 columns]

In [40]:
data.columns = [
    'surgery', 'age', 'hospital_number', 'rectal_t', 'pulse', 'respiratory_rate', 'extremities_t',
    'peripheral_pulse', 'mucous_membranes', 'capillary_time', 'pain', 'peristalsis', 'abdominal_distension', 
    'nasogastric_tube', 'reflux', 'reflux_PH', 'rectal_examination', 'abdomen', 'packed_volume', 
    'total_protein', 'abdominocentesis_appearance', 'abdomcentesis_protein', 'outcome', 'surgical_lesion', 
    'lesion1', 'lesion2', 'lesion3', 'cp_data',
]

In [41]:
data_column = data.drop(
    ['hospital_number', 
     'peripheral_pulse', 
     'mucous_membranes', 
     'capillary_time', 
     'peristalsis', 
     'abdominal_distension', 
     'nasogastric_tube', 
     'reflux', 
     'reflux_PH', 
     'rectal_examination', 
     'abdomen', 
     'packed_volume', 
     'total_protein', 
     'abdominocentesis_appearance', 
     'abdomcentesis_protein', 
     'surgical_lesion', 
     'lesion1', 
     'lesion2', 
     'lesion3', 
     'cp_data'
    ], axis = 1)
data_column.head(5)

surgery  age  rectal_t  pulse  respiratory_rate  extremities_t  pain  \
0      1.0    1      39.2   88.0              20.0            NaN   3.0   
1      2.0    1      38.3   40.0              24.0            1.0   3.0   
2      1.0    9      39.1  164.0              84.0            4.0   2.0   
3      2.0    1      37.3  104.0              35.0            NaN   NaN   
4      2.0    1       NaN    NaN               NaN            2.0   2.0   

   outcome  
0      3.0  
1      1.0  
2      2.0  
3      2.0  
4      1.0

## Задание 2. Первичное изучение данных
Проанализировать значения по столбцам, рассчитать базовые статистики, найти выбросы.

- Уникальные значения столбцов

In [110]:
data_column['age'].unique()

array([1, 2], dtype=int64)

In [111]:
data_column['surgery'].unique()

array([ 1.,  2., nan])

In [112]:
data_column['rectal_t'].unique()

array([39.2 , 38.3 , 39.1 , 37.3 , 38.6 , 37.9 , 38.  , 38.1 , 37.2 ,
       38.2 , 37.6 , 37.5 , 39.4 , 39.9 , 38.4 , 37.8 , 37.7 , 38.7 ,
       39.  , 35.4 , 38.9 , 37.4 , 40.3 , 39.3 , 38.5 , 37.  , 39.7 ,
       36.4 , 38.8 , 39.6 , 38.65, 36.8 , 39.5 , 36.5 , 36.  , 37.1 ,
       38.05, 38.25, 36.1 , 36.6 , 40.8 , 36.9 , 40.  ])

In [46]:
data_column['pulse'].unique()

array([ 88.,  40., 164., 104.,  nan,  48.,  60.,  80.,  90.,  66.,  72.,
        42.,  92.,  76.,  96., 128.,  64., 110., 130., 108., 100., 112.,
        52., 146., 150., 120., 140.,  84.,  46., 114., 160.,  54.,  56.,
        38.,  98.,  50.,  44.,  70.,  78.,  49.,  30., 136., 132.,  65.,
        86., 129.,  68.,  36.,  45., 124., 184.,  75.,  82.])

In [47]:
data_column['respiratory_rate'].unique()

array([20., 24., 84., 35., nan, 16., 36., 12., 52., 28., 48., 21., 60.,
       34., 42., 30., 96., 72., 15., 44., 32., 22., 18., 80., 40., 10.,
       51., 68., 66.,  9., 14., 90.,  8., 23., 58., 13., 70., 26., 88.,
       25., 50.])

In [113]:
data_column['extremities_t'].unique()

array([nan,  1.,  4.,  2.,  3.])

In [114]:
data_column['pain'].unique()

array([3., 2., 4., 5., 1.])

### - respiratory_rate в этом столбце значения указаны в десятках, в то время как в описании норма 8-10. То есть надо данный столбец разделить на 10.
### - age тут явная ошибка, вместо 2 стоит 9. По описанию в этом столбце есть значения 1 и 2. В нашей таблице 1 и 9. То есть 9 заменить на 2.
### - По остальным на первый взгляд нет ошибок.

#### Пересчет столбцов указанных выше 'respiratory_rate', 'age'

In [50]:
data_column['respiratory_rate'] = data_column['respiratory_rate'] / 10

In [51]:
#data_column.head()

In [52]:
data_column.loc[(data_column.age > 1), 'age'] = 2

In [53]:
#data_column.sort_values('age')

## Расчет базовых статистик

In [54]:
data_column.describe()

surgery         age    rectal_t       pulse  respiratory_rate  \
count  298.000000  299.000000  239.000000  275.000000        241.000000   
mean     1.395973    1.080268   38.166527   71.934545          3.042739   
std      0.489881    0.272162    0.733508   28.680522          1.767826   
min      1.000000    1.000000   35.400000   30.000000          0.800000   
25%      1.000000    1.000000   37.800000   48.000000          1.800000   
50%      1.000000    1.000000   38.200000   64.000000          2.400000   
75%      2.000000    1.000000   38.500000   88.000000          3.600000   
max      2.000000    2.000000   40.800000  184.000000          9.600000   

       extremities_t        pain     outcome  
count     243.000000  244.000000  298.000000  
mean        2.345679    2.942623    1.550336  
std         1.046369    1.303993    0.737967  
min         1.000000    1.000000    1.000000  
25%         1.000000    2.000000    1.000000  
50%         3.000000    3.000000    1.000000  
75%         3.000000    4.000000    2.000000  
max         4.000000    5.000000    3.000000

# Выбросы по столбцам

In [55]:
# выбросы в surgery
q1 = data_column['surgery'].quantile(0.25)
q3 = data_column['surgery'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr) 
upper_bound = q3 + (1.5 * iqr)
remove_outliers = data_column[data_column['surgery'].between(lower_bound, upper_bound, inclusive=True)]
remove_outliers
pd.concat([data_column, remove_outliers]).drop_duplicates(keep=False)

D:\ANACONDA\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  import sys


surgery  age  rectal_t  pulse  respiratory_rate  extremities_t  pain  \
131      NaN    1      38.0   48.0               2.0            3.0   4.0   

     outcome  
131      NaN

q1 = data_column['age'].quantile(0.25)
q3 = data_column['age'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr)
upper_bound = q3 + (1.5 * iqr)
remove_outliers_1 = data_column[data_column['age'].between(lower_bound, upper_bound, inclusive=True)]
pd.concat([data_column, remove_outliers_1]).drop_duplicates(keep=False)

In [56]:
q1 = data_column['rectal_t'].quantile(0.25)
q3 = data_column['rectal_t'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr) 
upper_bound = q3 + (1.5 * iqr)
remove_outliers_2 = data_column[data_column['rectal_t'].between(lower_bound, upper_bound, inclusive=True)]
pd.concat([data_column, remove_outliers_2]).drop_duplicates(keep=False).sort_values('rectal_t').head(20)

D:\ANACONDA\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  


surgery  age  rectal_t  pulse  respiratory_rate  extremities_t  pain  \
43       1.0    1      35.4  140.0               2.4            3.0   4.0   
140      2.0    1      36.0   42.0               3.0            NaN   NaN   
237      2.0    1      36.1   88.0               NaN            3.0   3.0   
79       1.0    1      36.4   98.0               3.5            3.0   4.0   
117      1.0    1      36.5   78.0               3.0            1.0   5.0   
297      1.0    1      36.5  100.0               2.4            3.0   3.0   
250      2.0    1      36.6   42.0               1.8            3.0   1.0   
98       2.0    1      39.6  108.0               5.1            3.0   2.0   
74       1.0    2      39.7  100.0               NaN            3.0   2.0   
19       1.0    1      39.9   72.0               6.0            1.0   5.0   
280      2.0    1      40.0   78.0               NaN            3.0   2.0   
53       2.0    1      40.3  114.0               3.6            3.0   2.0   
90       2.0    1      40.3  114.0               3.6            3.0   2.0   
258      1.0    1      40.8   72.0               4.2            3.0   2.0   
4        2.0    1       NaN    NaN               NaN            2.0   2.0   
6        1.0    1       NaN   60.0               NaN            3.0   NaN   
7        2.0    1       NaN   80.0               3.6            3.0   4.0   
15       1.0    2       NaN  128.0               3.6            3.0   4.0   
34       2.0    1       NaN  104.0               2.4            4.0   4.0   
39       1.0    1       NaN   88.0               NaN            3.0   5.0   

     outcome  
43       3.0  
140      2.0  
237      3.0  
79       2.0  
117      1.0  
297      1.0  
250      2.0  
98       1.0  
74       3.0  
19       1.0  
280      2.0  
53       3.0  
90       2.0  
258      2.0  
4        1.0  
6        2.0  
7        3.0  
15       2.0  
34       3.0  
39       2.0

In [57]:
q1 = data_column['pulse'].quantile(0.25)
q3 = data_column['pulse'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr) 
upper_bound = q3 + (1.5 * iqr)
remove_outliers_3 = data_column[data_column['pulse'].between(lower_bound, upper_bound, inclusive=True)]
pd.concat([data_column, remove_outliers_3]).drop_duplicates(keep=False).sort_values('pulse')

D:\ANACONDA\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  


surgery  age  rectal_t  pulse  respiratory_rate  extremities_t  pain  \
40       2.0    2      39.0  150.0               7.2            NaN   NaN   
274      1.0    2      38.8  150.0               5.0            1.0   5.0   
54       1.0    2      38.6  160.0               2.0            3.0   3.0   
2        1.0    2      39.1  164.0               8.4            4.0   2.0   
254      1.0    2      38.8  184.0               8.4            1.0   4.0   
4        2.0    1       NaN    NaN               NaN            2.0   2.0   
51       2.0    1       NaN    NaN               NaN            1.0   1.0   
57       1.0    1       NaN    NaN               2.0            4.0   5.0   
73       1.0    2       NaN    NaN               NaN            NaN   NaN   
92       2.0    1       NaN    NaN               NaN            3.0   5.0   
114      2.0    1       NaN    NaN               4.0            3.0   3.0   
116      2.0    1      39.5    NaN               NaN            3.0   3.0   
125      1.0    1      38.7    NaN               NaN            3.0   5.0   
150      1.0    1      39.3    NaN               NaN            4.0   4.0   
158      2.0    1       NaN    NaN               1.2            1.0   2.0   
159      1.0    1       NaN    NaN               NaN            NaN   4.0   
173      2.0    1       NaN    NaN               NaN            3.0   4.0   
203      1.0    1      39.2    NaN               2.3            3.0   4.0   
215      2.0    1       NaN    NaN               NaN            NaN   NaN   
226      1.0    2       NaN    NaN               NaN            NaN   NaN   

     outcome  
40       1.0  
274      2.0  
54       2.0  
2        2.0  
254      2.0  
4        1.0  
51       1.0  
57       2.0  
73       2.0  
92       2.0  
114      1.0  
116      3.0  
125      1.0  
150      2.0  
158      1.0  
159      1.0  
173      2.0  
203      1.0  
215      1.0  
226      1.0

In [58]:
q1 = data_column['respiratory_rate'].quantile(0.25)
q3 = data_column['respiratory_rate'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr) 
upper_bound = q3 + (1.5 * iqr)
remove_outliers_4 = data_column[data_column['respiratory_rate'].between(lower_bound, upper_bound, inclusive=True)]
pd.concat([data_column, remove_outliers_4]).drop_duplicates(keep=False).sort_values('respiratory_rate')

D:\ANACONDA\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  


surgery  age  rectal_t  pulse  respiratory_rate  extremities_t  pain  \
119      1.0    1      39.4   54.0               6.6            1.0   2.0   
102      1.0    2      38.0  140.0               6.8            1.0   3.0   
124      1.0    1      38.0   42.0               6.8            4.0   3.0   
264      2.0    1       NaN   56.0               6.8            3.0   3.0   
228      1.0    2      38.5  120.0               7.0            NaN   NaN   
..       ...  ...       ...    ...               ...            ...   ...   
255      1.0    1      37.5   72.0               NaN            2.0   2.0   
270      1.0    1      37.7   80.0               NaN            3.0   5.0   
273      1.0    1       NaN   76.0               NaN            NaN   NaN   
280      2.0    1      40.0   78.0               NaN            3.0   2.0   
283      2.0    1      38.5   54.0               NaN            1.0   3.0   

     outcome  
119      1.0  
102      1.0  
124      1.0  
264      3.0  
228      1.0  
..       ...  
255      3.0  
270      1.0  
273      3.0  
280      2.0  
283      1.0  

[62 rows x 8 columns]

In [128]:
#Удаляем по 1-й строке со значением NAN из столбцов outcome, surgery. Одна строка не исказит статистику в данном случае.
data_column[['surgery', 'outcome']].dropna()

surgery  outcome
0        1.0      3.0
1        2.0      1.0
2        1.0      2.0
3        2.0      2.0
4        2.0      1.0
..       ...      ...
294      1.0      3.0
295      2.0      3.0
296      1.0      2.0
297      1.0      1.0
298      1.0      3.0

[298 rows x 2 columns]

In [130]:
data_column.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   surgery           298 non-null    float64
 1   age               299 non-null    int64  
 2   rectal_t          299 non-null    float64
 3   pulse             299 non-null    float64
 4   respiratory_rate  299 non-null    float64
 5   extremities_t     298 non-null    float64
 6   pain              299 non-null    float64
 7   outcome           298 non-null    float64
dtypes: float64(7), int64(1)
memory usage: 18.8 KB


## Замена значений NAN столбца rectal_t

In [131]:
#data_column['rectal_t'].describe()

## значение моды близко к середине и медиане, в этом случае можно попробовать подставить каждое из трех значений и посмотреть как это повляет на показатели. Я попробую заменить медианой и модой.

In [132]:
data_column['rectal_t'].fillna(data_column.groupby(['extremities_t', 'pain'])['rectal_t'].transform('median'), inplace=True)

In [133]:
print(data_column.groupby(['extremities_t', 'pulse'])['rectal_t'].median())

extremities_t  pulse
1.0            36.0     37.75
               40.0     38.20
               42.0     38.30
               44.0     38.00
               46.0     38.60
                        ...  
4.0            110.0    39.40
               112.0    38.40
               120.0    38.60
               130.0    38.20
               164.0    39.10
Name: rectal_t, Length: 114, dtype: float64


In [134]:
data_column['rectal_t'].fillna(data_column.groupby(['extremities_t', 'pulse'])['rectal_t'].transform('median'), inplace=True)

In [135]:
data_column['rectal_t'].describe()

count    299.000000
mean      38.171237
std        0.676791
min       35.400000
25%       37.900000
50%       38.100000
75%       38.500000
max       40.800000
Name: rectal_t, dtype: float64

In [136]:
# оставшиеся заменю модой
data_column['rectal_t'].fillna(data_column['rectal_t'].mode()[0], inplace=True)
data_column['rectal_t'].describe()

count    299.000000
mean      38.171237
std        0.676791
min       35.400000
25%       37.900000
50%       38.100000
75%       38.500000
max       40.800000
Name: rectal_t, dtype: float64

## Замена значений NAN столбца pulse

In [137]:
data_column['pulse'].describe()

count    299.000000
mean      70.200669
std       28.170261
min       30.000000
25%       48.000000
50%       60.000000
75%       88.000000
max      184.000000
Name: pulse, dtype: float64

In [138]:
print(data_column.groupby('respiratory_rate')['pulse'].median())

respiratory_rate
0.8     40.0
0.9     40.0
1.0     44.0
1.2     48.0
1.3    112.0
1.4     49.0
1.5     60.0
1.6     50.0
1.8     54.0
2.0     52.0
2.1     54.0
2.2     79.0
2.3     74.0
2.4     62.0
2.5     40.0
2.6     42.0
2.8     70.0
3.0     75.0
3.2     60.0
3.4     42.0
3.5     98.0
3.6     80.0
4.0     72.0
4.2     66.0
4.4     80.0
4.8     60.0
5.0     80.0
5.1    104.0
5.2     72.0
5.8     88.0
6.0    108.0
6.6     54.0
6.8     52.0
7.0    120.0
7.2    150.0
8.0     88.0
8.4    164.0
8.8    110.0
9.0     64.0
9.6     88.0
Name: pulse, dtype: float64


In [139]:
data_column['pulse'].fillna(data_column.groupby('respiratory_rate')['pulse'].transform('median'), inplace=True)
data_column['pulse'].describe()

count    299.000000
mean      70.200669
std       28.170261
min       30.000000
25%       48.000000
50%       60.000000
75%       88.000000
max      184.000000
Name: pulse, dtype: float64

In [140]:
data_column['pulse'].fillna(data_column['pulse'].mode()[0], inplace=True)
data_column['pulse'].describe()

count    299.000000
mean      70.200669
std       28.170261
min       30.000000
25%       48.000000
50%       60.000000
75%       88.000000
max      184.000000
Name: pulse, dtype: float64

## Замена значений NAN столбца respiratory_rate

In [141]:
#print(data_column.groupby('pulse')['respiratory_rate'].median())

In [142]:
data_column['respiratory_rate'].describe()

count    299.000000
mean       3.049498
std        1.799988
min        0.800000
25%        1.800000
50%        2.400000
75%        3.600000
max        9.600000
Name: respiratory_rate, dtype: float64

In [143]:
data_column['respiratory_rate'].fillna(method='ffill', inplace=True)

In [144]:
#print(data_column.groupby('pulse')['respiratory_rate'].median())

In [145]:
data_column['respiratory_rate'].describe()

count    299.000000
mean       3.049498
std        1.799988
min        0.800000
25%        1.800000
50%        2.400000
75%        3.600000
max        9.600000
Name: respiratory_rate, dtype: float64

## Замена значений NAN столбца extremities_t

In [146]:
print(data_column.groupby('rectal_t')['extremities_t'].median())

rectal_t
35.40    3.0
36.00    3.0
36.10    3.0
36.40    3.0
36.50    2.0
36.60    3.0
36.80    2.0
36.90    2.0
37.00    2.0
37.10    3.0
37.20    3.0
37.30    3.0
37.40    3.0
37.50    2.5
37.60    3.0
37.70    2.0
37.80    1.0
37.90    3.0
38.00    3.0
38.05    3.0
38.10    3.0
38.20    1.0
38.25    2.0
38.30    2.0
38.40    2.0
38.50    3.0
38.60    2.0
38.65    3.0
38.70    2.5
38.80    1.0
38.90    3.0
39.00    3.0
39.10    3.0
39.20    3.5
39.30    2.0
39.40    1.0
39.50    3.0
39.60    3.0
39.70    3.0
39.90    1.0
40.00    3.0
40.30    3.0
40.80    3.0
Name: extremities_t, dtype: float64


In [147]:
data_column['extremities_t'].describe()

count    298.000000
mean       2.365772
std        1.043064
min        1.000000
25%        1.000000
50%        3.000000
75%        3.000000
max        4.000000
Name: extremities_t, dtype: float64

In [148]:
data_column['extremities_t'].fillna(method='ffill', inplace=True)

In [149]:
data_column['extremities_t'].describe()

count    298.000000
mean       2.365772
std        1.043064
min        1.000000
25%        1.000000
50%        3.000000
75%        3.000000
max        4.000000
Name: extremities_t, dtype: float64

## Замена значений NAN столбца pain

In [150]:
print(data_column.groupby('rectal_t')['pain'].median())

rectal_t
35.40    4.0
36.00    2.0
36.10    3.0
36.40    4.0
36.50    4.0
36.60    1.0
36.80    1.0
36.90    1.0
37.00    3.5
37.10    3.0
37.20    3.0
37.30    2.5
37.40    3.0
37.50    3.0
37.60    3.0
37.70    3.0
37.80    2.0
37.90    3.0
38.00    4.0
38.05    4.0
38.10    3.0
38.20    3.0
38.25    4.0
38.30    2.5
38.40    2.0
38.50    2.5
38.60    2.0
38.65    2.0
38.70    3.0
38.80    3.0
38.90    2.0
39.00    3.0
39.10    2.0
39.20    3.0
39.30    2.0
39.40    2.0
39.50    3.5
39.60    2.0
39.70    2.0
39.90    5.0
40.00    3.0
40.30    2.0
40.80    2.0
Name: pain, dtype: float64


In [151]:
data_column['pain'].describe()

count    299.000000
mean       2.939799
std        1.304248
min        1.000000
25%        2.000000
50%        3.000000
75%        4.000000
max        5.000000
Name: pain, dtype: float64

In [152]:
data_column['pain'].fillna(method='ffill', inplace=True)

In [153]:
data_column['pain'].describe()

count    299.000000
mean       2.939799
std        1.304248
min        1.000000
25%        2.000000
50%        3.000000
75%        4.000000
max        5.000000
Name: pain, dtype: float64

In [154]:

data_column.dropna()

surgery  age  rectal_t  pulse  respiratory_rate  extremities_t  pain  \
1        2.0    1      38.3   40.0               2.4            1.0   3.0   
2        1.0    2      39.1  164.0               8.4            4.0   2.0   
3        2.0    1      37.3  104.0               3.5            4.0   2.0   
4        2.0    1      38.6   48.0               3.5            2.0   2.0   
5        1.0    1      37.9   48.0               1.6            1.0   3.0   
..       ...  ...       ...    ...               ...            ...   ...   
294      1.0    1      38.5  120.0               7.0            4.0   2.0   
295      2.0    1      37.2   72.0               2.4            3.0   4.0   
296      1.0    1      37.5   72.0               3.0            4.0   4.0   
297      1.0    1      36.5  100.0               2.4            3.0   3.0   
298      1.0    1      37.2   40.0               2.0            3.0   3.0   

     outcome  
1        1.0  
2        2.0  
3        2.0  
4        1.0  
5        1.0  
..       ...  
294      3.0  
295      3.0  
296      2.0  
297      1.0  
298      3.0  

[297 rows x 8 columns]